
PyTorch是什么?
================

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy的替代品，可以使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台

In [1]:
# 首先要引入相关的包
import torch
import numpy as np
#打印一下版本
torch.__version__

'2.3.1+cu121'

# 张量(Tensor)
张量的英文是Tensor，它是PyTorch里面基础的运算单位，与Numpy的ndarray相同都表示的是一个多维的矩阵。
与ndarray的最大区别就是，PyTorch的Tensor可以在 GPU 上运行，而 numpy 的 ndarray 只能在 CPU 上运行，在GPU上运行大大加快了运算速度。

下面我们生成一个简单的张量

In [2]:
x = torch.rand(2, 3)
x

tensor([[0.4862, 0.0959, 0.4101],
        [0.8837, 0.6365, 0.2752]])

以上生成了一个，2行3列的的矩阵，我们看一下他的大小：

In [3]:
# 可以使用与numpy相同的shape属性查看
print(x.shape)
# 也可以使用size()函数，返回的结果都是相同的
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


张量（Tensor）是一个定义在一些向量空间和一些对偶空间的笛卡儿积上的多重线性映射，其坐标是|n|维空间内，有|n|个分量的一种量， 其中每个分量都是坐标的函数， 而在坐标变换时，这些分量也依照某些规则作线性变换。r称为该张量的秩或阶（与矩阵的秩和阶均无关系）。 (来自百度百科)

下面我们来生成一些多维的张量：

In [4]:
y=torch.rand(2,3,4,5)
print(y.size())
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.5562, 0.3842, 0.2514, 0.4940, 0.5484],
          [0.9414, 0.5889, 0.1684, 0.3432, 0.7726],
          [0.6179, 0.3233, 0.8470, 0.2098, 0.6997],
          [0.8537, 0.1483, 0.5064, 0.0885, 0.7669]],

         [[0.2402, 0.2539, 0.8411, 0.2927, 0.9911],
          [0.0589, 0.8525, 0.1928, 0.4497, 0.6297],
          [0.6905, 0.4514, 0.2092, 0.3016, 0.4565],
          [0.5864, 0.7645, 0.8926, 0.2744, 0.3461]],

         [[0.3078, 0.5705, 0.9848, 0.9559, 0.1580],
          [0.0366, 0.0463, 0.8166, 0.1174, 0.4081],
          [0.8139, 0.3438, 0.8362, 0.1651, 0.9217],
          [0.6922, 0.9159, 0.0387, 0.6195, 0.3690]]],


        [[[0.7739, 0.8689, 0.6118, 0.5030, 0.1638],
          [0.5203, 0.1606, 0.2875, 0.5151, 0.1226],
          [0.1190, 0.6046, 0.7995, 0.0946, 0.9164],
          [0.9598, 0.6774, 0.1394, 0.5881, 0.7331]],

         [[0.0325, 0.1449, 0.6996, 0.9127, 0.1206],
          [0.3737, 0.2166, 0.4211, 0.2164, 0.3164],
          [0.8113, 0.7959, 0.1772, 0.6531, 0.8943],
  

在同构的意义下，第零阶张量 （r = 0） 为标量 （Scalar），第一阶张量 （r = 1） 为向量 （Vector）， 第二阶张量 （r = 2） 则成为矩阵 （Matrix），第三阶以上的统称为多维张量。

其中要特别注意的就是标量，我们先生成一个标量：


In [5]:
#我们直接使用现有数字生成
scalar =torch.tensor(3.1433223)
print(scalar)
#打印标量的大小
scalar.size()

tensor(3.1433)


torch.Size([])

对于标量，我们可以直接使用 .item() 从中取出其对应的python对象的数值

In [6]:
scalar.item()

3.143322229385376

特别的：如果张量中只有一个元素的tensor也可以调用`tensor.item`方法

In [7]:
tensor = torch.tensor([3.1433223]) 
print(tensor)
tensor.size()

tensor([3.1433])


torch.Size([1])

In [8]:
tensor.item()

3.143322229385376

### 基本类型
Tensor的基本数据类型有五种：
- 32位浮点型：torch.FloatTensor。 (默认)
- 64位整型：torch.LongTensor。
- 32位整型：torch.IntTensor。
- 16位整型：torch.ShortTensor。
- 64位浮点型：torch.DoubleTensor。

除以上数字类型外，还有
byte和chart型

In [9]:
long=tensor.long()
long

tensor([3])

In [10]:
half=tensor.half()
half

tensor([3.1426], dtype=torch.float16)

In [11]:
int_t=tensor.int()
int_t

tensor([3], dtype=torch.int32)

In [12]:
flo = tensor.float()
flo

tensor([3.1433])

In [13]:
short = tensor.short()
short

tensor([3], dtype=torch.int16)

In [14]:
ch = tensor.char()
ch

tensor([3], dtype=torch.int8)

In [15]:
bt = tensor.byte()
bt

tensor([3], dtype=torch.uint8)

### Numpy转换
使用numpy方法将Tensor转为ndarray

In [16]:
a = torch.randn((3, 2))
# tensor转化为numpy
numpy_a = a.numpy()
print(numpy_a)

[[ 1.0321832   0.622237  ]
 [ 0.0309437  -0.32825637]
 [ 0.8479681   1.8006579 ]]


numpy转化为Tensor


In [17]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[ 1.0322,  0.6222],
        [ 0.0309, -0.3283],
        [ 0.8480,  1.8007]])

***Tensor和numpy对象共享内存，所以他们之间的转换很快，而且几乎不会消耗什么资源。但这也意味着，如果其中一个变了，另外一个也会随之改变。***

### 设备间转换
使用``.to`` 方法 可以将Tensor移动到任何设备中

In [18]:
cpu_a=torch.rand(4, 3)
cpu_a.type()

'torch.FloatTensor'

使用.to("cuda")，可以将Tensor移动到GPU设备中。

In [19]:
print(torch.cuda.is_available())
gpu_a=cpu_a.to("cuda")
gpu_a.type()

True


'torch.cuda.FloatTensor'

使用.to("mps")，可以将Tensor移动到M系列芯片MAC的加速计算框架上。

In [ ]:
print(torch.mps.is_available())
gpu_a=cpu_a.to("mps")
gpu_a.type()

'torch.mps.FloatTensor'

使用.cpu方法将tensor移动到cpu

In [20]:
cpu_b=gpu_a.cpu()
cpu_b.type()

'torch.FloatTensor'

``注意``：
所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量



### 初始化
Pytorch中有许多默认的初始化方法可以使用

In [21]:
# 使用[0,1]均匀分布随机初始化二维数组
rnd = torch.rand(5, 3)
rnd

tensor([[0.6064, 0.0511, 0.9958],
        [0.4041, 0.8075, 0.5598],
        [0.5235, 0.5278, 0.8778],
        [0.6740, 0.3439, 0.2831],
        [0.6060, 0.2081, 0.4131]])

In [22]:
##初始化，使用1填充
one = torch.ones(2, 2)
one

tensor([[1., 1.],
        [1., 1.]])

In [23]:
##初始化，使用0填充
zero=torch.zeros(2,2)
zero

tensor([[0., 0.],
        [0., 0.]])

In [24]:
#初始化一个单位矩阵，即对角线为1 其他为0
eye=torch.eye(2,2)
eye

tensor([[1., 0.],
        [0., 1.]])

### 常用方法
PyTorch中对张量的操作api 和 NumPy 非常相似，如果熟悉 NumPy 中的操作，那么他们二者基本是一致的：

In [25]:
x = torch.randn(3, 3)
print(x)

tensor([[ 0.4541, -1.5342, -1.5037],
        [ 0.6858, -0.8828,  0.1743],
        [ 0.0505, -1.1970, -1.3877]])


In [26]:
# 沿着行取最大值
max_value, max_idx = torch.max(x, dim=1)
print(max_value, max_idx)

tensor([0.4541, 0.6858, 0.0505]) tensor([0, 0, 0])


In [27]:
# 每行 x 求和
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([-2.5838, -0.0226, -2.5341])


In [28]:
y=torch.randn(3, 3)
z = x + y
print(z)

tensor([[-0.6602, -3.2611, -1.9483],
        [-0.3524, -1.4407, -0.4963],
        [ 0.5742,  0.0713, -1.6183]])


以_为结尾的，均会改变调用值

In [29]:
# add 完成后x的值改变了
x.add_(y)
print(x)

tensor([[-0.6602, -3.2611, -1.9483],
        [-0.3524, -1.4407, -0.4963],
        [ 0.5742,  0.0713, -1.6183]])


张量的基本操作都介绍的的差不多了，下面介绍PyTorch的自动求导机制

# 使用PyTorch计算梯度数值

PyTorch的Autograd模块实现了深度学习的算法中的向传播求导数，在张量（Tensor类）上的所有操作，Autograd都能为他们自动提供微分，简化了手动计算导数的复杂过程。

在0.4以前的版本中，Pytorch 使用 Variable 类来自动计算所有的梯度。Variable类主要包含三个属性：
data：保存Variable所包含的Tensor；grad：保存data对应的梯度，grad也是个Variable，而不是Tensor，它和data的形状一样；grad_fn：指向一个Function对象，这个Function用来反向传播计算输入的梯度。


从0.4起， Variable 正式合并入Tensor类，通过Variable嵌套实现的自动微分功能已经整合进入了Tensor类中。虽然为了代码的兼容性还是可以使用Variable(tensor)这种方式进行嵌套，但是这个操作其实什么都没做。

所以，以后的代码建议直接使用Tensor类进行操作，因为官方文档中已经将Variable设置成过期模块。

要想通过Tensor类本身就支持了使用autograd功能，只需要设置.requires_grad=True

Variable类中的的grad和grad_fn属性已经整合进入了Tensor类中

## Autograd

在张量创建时，通过设置 requires_grad 标识为Ture来告诉Pytorch需要对该张量进行自动求导，PyTorch会记录该张量的每一步操作历史并自动计算

In [30]:
x = torch.rand(5, 5, requires_grad=True)
x

tensor([[0.4562, 0.5391, 0.5784, 0.9791, 0.5348],
        [0.4466, 0.1700, 0.7257, 0.0305, 0.3195],
        [0.8016, 0.9556, 0.4417, 0.6479, 0.1599],
        [0.6445, 0.1676, 0.7844, 0.8477, 0.3878],
        [0.2941, 0.7939, 0.3571, 0.2405, 0.6296]], requires_grad=True)

In [31]:
y = torch.rand(5, 5, requires_grad=True)
y

tensor([[0.7623, 0.1894, 0.7829, 0.0639, 0.0454],
        [0.5192, 0.9582, 0.2377, 0.4569, 0.7393],
        [0.9676, 0.7729, 0.2908, 0.3283, 0.3356],
        [0.4077, 0.2330, 0.7772, 0.2610, 0.9602],
        [0.2165, 0.5694, 0.4174, 0.0278, 0.8129]], requires_grad=True)

PyTorch会自动追踪和记录对与张量的所有操作，当计算完成后调用.backward()方法自动计算梯度并且将计算结果保存到grad属性中。

In [32]:
z=torch.sum(x+y)
z

tensor(25.0674, grad_fn=<SumBackward0>)

在张量进行操作后，grad_fn已经被赋予了一个新的函数，这个函数引用了一个创建了这个Tensor类的Function对象。
Tensor和Function互相连接生成了一个非循环图，它记录并且编码了完整的计算历史。每个张量都有一个.grad_fn属性，如果这个张量是用户手动创建的那么这个张量的grad_fn是None。

下面我们来调用反向传播函数，计算其梯度

## 简单的自动求导

In [33]:
z.backward()
print(x.grad,y.grad)


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


如果Tensor类表示的是一个标量（即它包含一个元素的张量），则不需要为backward()指定任何参数，但是如果它有更多的元素，则需要指定一个gradient参数，它是形状匹配的张量。
以上的 `z.backward()`相当于是`z.backward(torch.tensor(1.))`的简写。
这种参数常出现在图像分类中的单标签分类，输出一个标量代表图像的标签。

## 复杂的自动求导

In [34]:
x = torch.rand(5, 5, requires_grad=True)
y = torch.rand(5, 5, requires_grad=True)
z= x**2+y**3
z

tensor([[0.8759, 0.8360, 0.1714, 0.7811, 0.0265],
        [0.3532, 0.1657, 0.0772, 1.3617, 0.1615],
        [1.5500, 0.2219, 0.6496, 1.2906, 1.1732],
        [0.0632, 0.9383, 0.8841, 0.0333, 0.0028],
        [0.0514, 0.9651, 0.4184, 0.4937, 0.2665]], grad_fn=<AddBackward0>)

In [35]:
#我们的返回值不是一个标量，所以需要输入一个大小相同的张量作为参数，这里我们用ones_like函数根据x生成一个张量
z.backward(torch.ones_like(x))
print(x.grad)

tensor([[1.6052, 0.6341, 0.7569, 1.7657, 0.3058],
        [0.3197, 0.8039, 0.5413, 1.7047, 0.5634],
        [1.6639, 0.6602, 1.0162, 1.9732, 1.7399],
        [0.1609, 1.1020, 1.8803, 0.3610, 0.1062],
        [0.4449, 1.4518, 1.2935, 1.3111, 0.9762]])


我们可以使用with torch.no_grad()上下文管理器临时禁止对已设置requires_grad=True的张量进行自动求导。这个方法在测试集计算准确率的时候会经常用到，例如：

In [36]:
with torch.no_grad():
    print((x +y*2).requires_grad)

False


使用.no_grad()进行嵌套后，代码不会跟踪历史记录，也就是说保存的这部分记录会减少内存的使用量并且会加快少许的运算速度。

# 神经网络包nn和优化器optm
torch.nn是专门为神经网络设计的模块化接口。nn构建于 Autograd之上，可用来定义和运行神经网络。
这里我们主要介绍几个一些常用的类

**约定：torch.nn 我们为了方便使用，会为他设置别名为nn，本章除nn以外还有其他的命名约定**

In [37]:
# 首先要引入相关的包
import torch
# 引入torch.nn并指定别名
import torch.nn as nn
#打印一下版本
torch.__version__

'2.3.1+cu121'

除了nn别名以外，我们还引用了nn.functional，这个包中包含了神经网络中使用的一些常用函数，这些函数的特点是，不具有可学习的参数(如ReLU，pool，DropOut等)，这些函数可以放在构造函数中，也可以不放，但是这里建议不放。

一般情况下我们会**将nn.functional 设置为大写的F**，这样缩写方便调用

In [38]:
import torch.nn.functional as F

## 定义一个网络
PyTorch中已经为我们准备好了现成的网络模型，只要继承nn.Module，并实现它的forward方法，PyTorch会根据autograd，自动实现backward函数，在forward函数中可使用任何tensor支持的函数，还可以使用if、for循环、print、log等Python语法，写法和标准的Python写法一致。

In [39]:
class Net(nn.Module):
    def __init__(self):
        # nn.Module子类的函数必须在构造函数中执行父类的构造函数
        super(Net, self).__init__()
        
        # 卷积层 '1'表示输入图片为单通道， '6'表示输出通道数，'3'表示卷积核为3*3
        self.conv1 = nn.Conv2d(1, 6, 3) 
        #线性层，输入1350个特征，输出10个特征
        self.fc1   = nn.Linear(1350, 10)  #这里的1350是如何计算的呢？这就要看后面的forward函数
    #正向传播 
    def forward(self, x): 
        print(x.size()) # 结果：[1, 1, 32, 32]
        # 卷积 -> 激活 -> 池化 
        x = self.conv1(x) #根据卷积的尺寸计算公式，计算结果是30，具体计算公式后面第二章第四节 卷积神经网络 有详细介绍。
        x = F.relu(x)
        print(x.size()) # 结果：[1, 6, 30, 30]
        x = F.max_pool2d(x, (2, 2)) #我们使用池化层，计算结果是15
        x = F.relu(x)
        print(x.size()) # 结果：[1, 6, 15, 15]
        # reshape，‘-1’表示自适应
        #这里做的就是压扁的操作 就是把后面的[1, 6, 15, 15]压扁，变为 [1, 1350]
        x = x.view(x.size()[0], -1) 
        print(x.size()) # 这里就是fc1层的的输入1350 
        x = self.fc1(x)        
        return x

net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=1350, out_features=10, bias=True)
)


网络的可学习参数通过net.parameters()返回

In [40]:
for parameters in net.parameters():
    print(parameters)

Parameter containing:
tensor([[[[-0.0007, -0.3033, -0.1665],
          [ 0.2051,  0.1831, -0.0097],
          [ 0.1502, -0.1062, -0.0263]]],


        [[[-0.0299, -0.1013,  0.1857],
          [ 0.2592,  0.3131, -0.0961],
          [ 0.1883,  0.0501, -0.1307]]],


        [[[-0.0781, -0.3174, -0.0590],
          [ 0.0132, -0.2880, -0.0644],
          [-0.2720, -0.1075,  0.1677]]],


        [[[ 0.3266,  0.2958,  0.3015],
          [ 0.1272,  0.1986, -0.1277],
          [ 0.3194,  0.3263,  0.1440]]],


        [[[ 0.0809, -0.0110, -0.2811],
          [-0.0859, -0.1482,  0.2395],
          [ 0.2147, -0.0443,  0.3265]]],


        [[[ 0.0770,  0.1275,  0.2770],
          [ 0.1241,  0.0377, -0.0944],
          [-0.1414, -0.0039, -0.0945]]]], requires_grad=True)
Parameter containing:
tensor([ 0.2325,  0.2301,  0.0603,  0.0476, -0.0230,  0.0546],
       requires_grad=True)
Parameter containing:
tensor([[-0.0195, -0.0057, -0.0251,  ...,  0.0091,  0.0087,  0.0015],
        [ 0.0081,  0.0157, -0

net.named_parameters可同时返回可学习的参数及名称。

In [41]:
for name,parameters in net.named_parameters():
    print(name,':',parameters.size())

conv1.weight : torch.Size([6, 1, 3, 3])
conv1.bias : torch.Size([6])
fc1.weight : torch.Size([10, 1350])
fc1.bias : torch.Size([10])


forward函数的输入和输出都是Tensor

In [42]:
input = torch.randn(1, 1, 32, 32) # 这里的对应前面fforward的输入是32
out = net(input)
out.size()

torch.Size([1, 1, 32, 32])
torch.Size([1, 6, 30, 30])
torch.Size([1, 6, 15, 15])
torch.Size([1, 1350])


torch.Size([1, 10])

In [43]:
input.size()

torch.Size([1, 1, 32, 32])

在反向传播前，先要将所有参数的梯度清零

In [44]:
net.zero_grad() 
out.backward(torch.ones(1,10)) # 反向传播的实现是PyTorch自动实现的，我们只要调用这个函数即可

**注意**:torch.nn只支持mini-batches，不支持一次只输入一个样本，即一次必须是一个batch。

也就是说，就算我们输入一个样本，也会对样本进行分批，所以，所有的输入都会增加一个维度，我们对比下刚才的input，nn中定义为3维，但是我们人工创建时多增加了一个维度，变为了4维，最前面的1即为batch-size

## 损失函数
在nn中PyTorch还预制了常用的损失函数，下面我们用MSELoss用来计算均方误差

In [45]:
y = torch.arange(0,10).view(1,10).float()
criterion = nn.MSELoss()
loss = criterion(out, y)
#loss是个scalar，我们可以直接用item获取到他的python类型的数值
print(loss.item()) 

29.1951961517334


## 优化器
在反向传播计算完所有参数的梯度后，还需要使用优化方法来更新网络的权重和参数，例如随机梯度下降法(SGD)的更新策略如下：

weight = weight - learning_rate * gradient

在torch.optim中实现大多数的优化方法，例如RMSProp、Adam、SGD等，下面我们使用SGD做个简单的样例

In [46]:
import torch.optim

In [47]:
out = net(input) # 这里调用的时候会打印出我们在forword函数中打印的x的大小
criterion = nn.MSELoss()
loss = criterion(out, y)
#新建一个优化器，SGD只需要要调整的参数和学习率
optimizer = torch.optim.SGD(net.parameters(), lr = 0.01)
# 先梯度清零(与net.zero_grad()效果一样)
optimizer.zero_grad() 
loss.backward()

#更新参数
optimizer.step()

torch.Size([1, 1, 32, 32])
torch.Size([1, 6, 30, 30])
torch.Size([1, 6, 15, 15])
torch.Size([1, 1350])


这样，神经网络的数据的一个完整的传播就已经通过PyTorch实现了，下面将介绍PyTorch提供的数据加载和处理工具，使用这些工具可以方便的处理所需要的数据。

# 数据的加载和预处理
PyTorch通过torch.utils.data对一般常用的数据加载进行了封装，可以很容易地实现多线程数据预读和批量加载。
并且torchvision已经预先实现了常用图像数据集，包括作业中使用过的CIFAR-10数据集，可通过torchvision.datasets方便的调用

## Dataset
Dataset是一个抽象类，为了能够方便的读取，需要将要使用的数据包装为Dataset类。
自定义的Dataset需要继承它并且实现两个成员方法：
1. `__getitem__()` 该方法定义用索引(`0` 到 `len(self)`)获取一条数据或一个样本
2. `__len__()` 该方法返回数据集的总长度

下面我们使用kaggle上的一个竞赛[bluebook for bulldozers](https://www.kaggle.com/c/bluebook-for-bulldozers/data)自定义一个数据集，为了方便介绍，我们使用里面的数据字典来做说明（因为条数少）

In [48]:
#引用
from torch.utils.data import Dataset
import pandas as pd

In [49]:
#定义一个数据集
class BulldozerDataset(Dataset):
    """ 数据集演示 """
    def __init__(self, csv_file):
        """实现初始化方法，在初始化的时候将数据读载入"""
        self.df=pd.read_csv(csv_file)
    def __len__(self):
        '''
        返回df的长度
        '''
        return len(self.df)
    def __getitem__(self, idx):
        '''
        根据 idx 返回一行数据
        '''
        return self.df.iloc[idx].SalePrice

至此，我们的数据集已经定义完成了，我们可以实例化一个对象访问它

In [50]:
ds_demo= BulldozerDataset('median_benchmark.csv')

我们可以直接使用如下命令查看数据集数据


In [51]:
#实现了 __len__ 方法所以可以直接使用len获取数据总数
len(ds_demo)

11573

In [52]:
#用索引可以直接访问对应的数据，对应 __getitem__ 方法
ds_demo[0]

24000.0

自定义的数据集已经创建好了，下面我们使用官方提供的数据载入器，读取数据
## Dataloader
DataLoader为我们提供了对Dataset的读取操作，常用参数有：batch_size(每个batch的大小)、 shuffle(是否进行shuffle操作)、 num_workers(加载数据的时候使用几个子进程)。下面做一个简单的操作

In [53]:
dl = torch.utils.data.DataLoader(ds_demo, batch_size=10, shuffle=True, num_workers=0)

DataLoader返回的是一个可迭代对象，我们可以使用迭代器分次获取数据

In [54]:
idata=iter(dl)
print(next(idata))

tensor([24000., 24000., 24000., 24000., 24000., 24000., 24000., 24000., 24000.,
        24000.], dtype=torch.float64)


常见的用法是使用for循环对其进行遍历

In [55]:
for i, data in enumerate(dl):
    print(i,data)
    # 为了节约空间，这里只循环一遍
    break

0 tensor([24000., 24000., 24000., 24000., 24000., 24000., 24000., 24000., 24000.,
        24000.], dtype=torch.float64)


我们已经可以通过dataset定义数据集，并使用Datalorder载入和遍历数据集，除了这些以外，PyTorch还提供能torcvision的计算机视觉扩展包，里面封装了
## torchvision 包
torchvision 是PyTorch中专门用来处理图像的库，PyTorch官网的安装教程中最后的pip install torchvision 就是安装这个包。

### torchvision.datasets
torchvision.datasets 可以理解为PyTorch团队自定义的dataset，这些dataset帮我们提前处理好了很多的图片数据集，我们拿来就可以直接使用：
- MNIST
- COCO
- Captions
- Detection
- LSUN
- ImageFolder
- Imagenet-12
- CIFAR
- STL10
- SVHN
- PhotoTour
我们可以直接使用，示例如下：

In [ ]:
import torchvision.datasets as datasets
trainset = datasets.MNIST(root='./data', # 表示 MNIST 数据的加载的目录
                                      train=True,  # 表示是否加载数据库的训练集，false的时候加载测试集
                                      download=True, # 表示是否自动下载 MNIST 数据集
                                      transform=None) # 表示是否需要对数据进行预处理，none为不进行预处理


### torchvision.models
torchvision不仅提供了常用图片数据集，还提供了训练好的模型，可以加载之后，直接使用，或者在进行迁移学习
torchvision.models模块的 子模块中包含以下模型结构。
- AlexNet
- VGG
- ResNet
- SqueezeNet
- DenseNet

In [ ]:
#我们直接可以使用训练好的模型，当然这个与datasets相同，都是需要从服务器下载的
import torchvision.models as models
resnet18 = models.resnet18(pretrained=True)

### torchvision.transforms
transforms 模块提供了一般的图像转换操作类，用作数据处理和数据增强

In [58]:
from torchvision import transforms as transforms
transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4),  #先四周填充0，在把图像随机裁剪成32*32
    transforms.RandomHorizontalFlip(),  #图像一半的概率翻转，一半的概率不翻转
    transforms.RandomRotation((-45,45)), #随机旋转
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.229, 0.224, 0.225)), #R,G,B每层的归一化用到的均值和方差
])

肯定有人会问：(0.485, 0.456, 0.406), (0.2023, 0.1994, 0.2010) 这几个数字是什么意思？

官方的这个帖子有详细的说明:
https://discuss.pytorch.org/t/normalization-in-the-mnist-example/457/21
这些都是根据ImageNet训练的归一化参数，可以直接使用，我们认为这个是固定值就可以